# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Z:/Vivado Projects/hw_debug/hw_debug.cache/wt} [current_project]
set_property parent.project_path {Z:/Vivado Projects/hw_debug/hw_debug.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {z:/Vivado Projects/hw_debug/hw_debug.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {Z:/Vivado Projects/hw_debug/hw_debug.srcs/sources_1/new/clk_div.v}
  {Z:/Vivado Projects/hw_debug/hw_debug.srcs/sources_1/new/flow_led.v}
  {Z:/Vivado Projects/hw_debug/hw_debug.srcs/sources_1/new/flow_led_top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{Z:/Vivado Projects/hw_debug/hw_debug.srcs/constrs_1/new/flow_led.xdc}}
set_property used_in_implementation false [get_files {{Z:/Vivado Projects/hw_debug/hw_debug.srcs/constrs_1/new/flow_led.xdc}}]


synth_design -top flow_led_top -part xc7a35tcsg324-1


write_checkpoint -force -noxdef flow_led_top.dcp

catch { report_utilization -file flow_led_top_utilization_synth.rpt -pb flow_led_top_utilization_synth.pb }
